[mgr]
show_hidden    = true
show_symlink   = true
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
linemode       = "none"

[opener]
edit = [
    { run = '${EDITOR:-nvim} "$@"', block = true },
]
play = [
    { run = 'mpv "$@"', orphan = true },
]

